### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by hinteor** [Serhiy-K/TFTGLCDAdapter#1]
I welcome you. I am going to repeat this project for my delta 3D printer. will there be any problems? and is it possible to repeat this project with a 50 pin display and is it possible to somehow make the touchscreen work instead of the encoder?

p.s. used google translator

**Comment by Serhiy-K** [comment]
Hi. There are no problems with this panel. It works as I planed. You may use display with different number of pins but you will need PCB correction for it. I do not like touchscreens and I do not plan add touchscreen support for this project.
