### ISSUE TITLE
can this adapter support other STM32F103 based touch screens?

### ISSUE THREAD

**Issue by edolis** [Serhiy-K/TFTGLCDAdapter#2]
Hi Serhiy-K
I am trying to adapt a Geeetech A30T to Marlin and one of the issues is the (undocumented) 3.2" touchscreen board (see attached a picture of the board).
It is based on STM32F103VET6.

On the visible side I can see a serial flash memory W25Q128JV, a touch controller TSC2046 and a voltage reference (I can remove the screen to access the other side, if required).
It's connected to the mainboard via a 4 wire connector.

Do you think that it can be made compatible for Marlin 2? This would make happy a lot of Geeetech users

Please give me your opinion. 
I can map the connections to reverse engineer a schematic if required - unfortunately i do not have any experience in making hardware ready for Marlin.
If really cannot be adapted, could it be replaced by your TFTGLCDAdapter (the mainboard is based on STM32F103 too, it should be a close relative to BOARD_GTM32_PRO_VB)?
Thanks for your attention an kind help.

![image](https://user-images.githubusercontent.com/2226075/100555377-5e661480-329b-11eb-8b48-bb2c2732c6b6.png)![PIC005](https://user-images.githubusercontent.com/2226075/100555320-eac40780-329a-11eb-9884-7d2193bdaae1.JPG)
![image](https://user-images.githubusercontent.com/2226075/100555399-8190c400-329b-11eb-9418-aecf43a41408.png)

**Comment by Serhiy-K** [comment]
Hi.
I can only talk about my version of the panel.
Yesterday I added touchscreen support to the firmware in the simplest possible way. I used a resistive touchscreen with a direct connection to the controller. At the same time, the interface remained practically unchanged - only "buttons" were added to change parameters.
I think my firmware can be adapted to your panel, but my panel is connected to mainboard via either SPI or I2C, and yours is most likely via UART. But on the motherboard diagram on the panel connector pinout, I see signals for SPI. In your photo, it corresponds to connector J6. Pinout: 1, 2 - GND, 3, 4 - UART(LCD_D13, LCD_D14), **MOSI, MISO, SCK, NSS**, GND, RESET, +5, +5.
If these SPI signals are connected to a panel-side controller, then it is possible to adapt my firmware without making any (or with minimal) hardware changes to the panel, but without SD support on the panel side. To support SD on the panel side, you will definitely need to make hardware changes. 
If the panel has no SPI signals connected to the J6 connector, then they can be taken from the SD card.
